Repository CliMA/CalibrateEDMF.jl, pull requests merged in 2022-03, with the labels that each got.

#237 Make nc file getter functions match more flexibly
  src/ReferenceModels.jl
Labels: Bug fix :bug: :hammer:

#244 Add an integration test for the SCT1 benchmark.
  .buildkite/pipeline.yml
  integration_tests/Bomex_integration_test_config.jl
  integration_tests/SCT1_integration_test_config.jl
  integration_tests/julia_parallel_test.jl
Labels: code coverage

#247 Remove ekp_experimental, use new EKP.jl version instead.
  Project.toml
  ekp_experimental/failsafe_inversion.jl
  src/Diagnostics.jl
  src/Pipeline.jl
  src/ReferenceStats.jl
Labels: House cleaning :broom:
