Repository CliMA/CalibrateEDMF.jl, pull requests merged in 2022-04, with the labels that each got.

#278 Make precompilation great again
  .buildkite/pipeline.yml
  Project.toml
  bors.toml
  experiments/scm_pycles_pipeline/README.md
  experiments/scm_pycles_pipeline/hpc_parallel/create_tc_so.jl
  experiments/scm_pycles_pipeline/hpc_parallel/ekp_calibration.sbatch
  experiments/scm_pycles_pipeline/hpc_parallel/init.sbatch
  experiments/scm_pycles_pipeline/hpc_parallel/precondition_prior.sbatch
  experiments/scm_pycles_pipeline/hpc_parallel/single_scm_eval.sbatch
  experiments/scm_pycles_pipeline/hpc_parallel/step_ekp.sbatch
  experiments/scm_pycles_pipeline/hpc_parallel/sysimage.sbatch
Labels: Performance :rocket:

#288 Add buildkite unit tests back in
  .buildkite/pipeline.yml
  bors.toml
Labels: Continuous Integration :gear:

#286 Fix and test issue #285
  .buildkite/pipeline.yml
  integration_tests/Het_batch_unscented_test_config.jl
  integration_tests/Manifest.toml
  integration_tests/julia_parallel_test.jl
  src/Diagnostics.jl
  src/NetCDFIO.jl
Labels: enhancement
